project:
  type: website

website:
  title: "quarto_site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About the Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

