project:
  type: website

website:
  title: "Body Forgot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator
    right:
      - icon: instagram
        href: https://instagram.com/bodyforgot
      - text: "![threads](threads.svg)"
        href: https://www.threads.net/@bodyforgot
      - text: "![amazon](amazon.svg)"
        href: https://www.amazon.com
      - icon: book
        href: https://www.bn.com
      #- icon: envelope-at
      #  href: send email
      #- icon: spotify
        #href:
      #- icon: youtube
    execute:
      freeze: auto

format:
  html:
    #theme: cyborg
    theme: quartz
    #theme: vapor
    css: styles.css
    toc: true
    #backgroundcolor: "blue"
    #foreground: "white"

editor: visual

