project:
  type: website

website:
  title: "Body Forgot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator
    right:
      - icon: instagram
        href: https://instagram.com/bodyforgot
      - icon: threads
        href: https://www.threads.net/@bodyforgot

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    #backgroundcolor: "blue"
    #foreground: "white"

editor: visual

