project:
  type: website

website:
  title: "The Body Forgot"
  #subtitle: "A Fun Children's Book about Chronic Illness & Friendshp"
  favicon: 9798992578812.jpg
  image: 9798992578812.jpg
  twitter-card: true
  description: "A fun children's book about chronic illness and disability, written by a disabled and chonicallly ill author"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator
      - href: faq.qmd
        text: Book Q&A
    right:
      - text: "![amazon](amazon.svg)"
        href: https://www.amazon.com
        aria-label: Amazon
      - href: https://www.barnesandnoble.com/w/the-body-forgot-casey-jayne/1147087554?ean=9798992578805
        aria-label: Barnes & Noble
        text: BN
      - icon: instagram
        href: https://instagram.com/bodyforgot
        aria-label: Instagram
      - text: "Email"
        url: mailto:bodyforgot@gmail.com

    execute:
      freeze: auto

format:
  html:
    theme: quartz
    css: styles.css
    toc: true


editor: visual

