project:
  type: website

website:
  title: "Body Forgot"
  favicon: 9798992578812.jpg
  image: 9798992578812.jpg
  twitter-card: true
  description: "A children's book about chronic illness and disability available May 5, 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About this Book
      - href: author.qmd
        text: About the Author
      - href: illustrator.qmd
        text: About the Illustrator
      - href: faq.qmd
        text: Book Q&A
    right:
      - icon: instagram
        href: https://instagram.com/bodyforgot
        aria-label: Instagram
      - text: "![threads](threads.svg)"
        href: https://www.threads.net/@bodyforgot
        aria-label: Threads
      - text: "![amazon](amazon.svg)"
        href: https://www.amazon.com
        aria-label: Amazon
      - href: https://www.barnesandnoble.com/w/the-body-forgot-casey-jayne/1147087554?ean=9798992578805
        aria-label: Barnes & Noble
        text: BN
      #- icon: envelope-at
      #  href: mailto:
      #- icon: spotify
        #href:
      #- icon: youtube
    execute:
      freeze: auto

format:
  html:
    #theme: cyborg
    theme: quartz
    #theme: vapor
    css: styles.css
    toc: true
    #backgroundcolor: "blue"
    #foreground: "white"

editor: visual

