---
title: "About the Characters & Invisible Disability"
---

##{.sidebar width="300px"}

## Why does Sheila use a wheelchair 
- Sheila has chronic pain as one of her symptoms and uses a wheelchair when the pain impairs her ability to walk.  Due to the fact that she can walk sometimes or some distances, she is known as an ambulatory wheelchair users.  Contrary to popular understanding, the majority of wheelchair users are ambulatory - though their ability to stand or walk may vary based on their level of symptoms at any given time. 

## What does Mr. Flores use to digest and why? 
- Mr. Flores uses an ostemy to help him digest food.  These are commonly used due to conditions such as irritable bowel disease, chrons disease, stomach cancers. or other illnesses requiring surgery on the digestive system. 

## Why didn't you refer to Alisha's hearing aids? 
- We chose to focus on aspects of chronic illness which young children would see or experience directly.  Hearing loss requiring hearing aids are not as easily seen by children and thus are usually learned about later due to their inconspicuousness, however we didn't want to leave them out! By giving Alisha hearing aids we hoped that some children would ask the adult reading to them what they were as an opportunity for deeper learning.

## Why didn't you state the names of each persons illness or disability? 
-  Firstly, by focusing only on symptoms and devices we were able to capture many more chronic illnesses in the experiences of these characters than would be possible if we were quite specific. 
- Secondly, the goal of the book is to show children that not all bodies work the same way and that we can still be friends, neighbors, and families with them with the focus being on support rather than disease. 
- Lastly, in order to make this book developmentally appropriate, we chose not to use too much medical language.  

## Why aren't any of your characters blind, deaf, or with limb difference? 
- We are one of many books about disability and we hope that you seek out more books and educational materials so that we can raise accepting and open-minded children. 

## Why does Rohan have two dads? 
- Love is love and all families rooted in love deserve our respect. 
